#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -z "$DISPLAY" ] && [ $(tty) = /dev/tty1 ]; then
	startx
fi

PS1='[\u@\h \W]\$ '

alias ls='ls --color=auto'
alias make='sudo make clean install'
alias makepkg='makepkg -si'
alias update='sudo pacman -Syu && sudo pamcan -Syyu'
alias wuni='sudo netctl start eduroam'
alias whome='sudo netctl start home'

